FROM php:8.3-cli-alpine

RUN apk add --no-cache icu-dev postgresql-dev \
    && docker-php-ext-install pdo_pgsql intl opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
